version: "3"
services:
 
  nginx: 
    depends_on: 
      - wordpress
    build: ./requirements/nginx/.
    image: nginx
    env_file:
    - .env
    ports:
    - "443:443"
    volumes:
    - wp-data:/var/www/wordpress/
  wordpress: 
    build: ./requirements/wordpress/.
    image: wordpress
    env_file:
    - .env
    ports:
    - "9000"
    volumes:
    - wp-data:/var/www/wordpress/

networks:
  inception_network:
    driver: bridge

volumes:
   wp-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/abbelhac/wp-data"
      o: bind

