version: "3"
services:
 
  nginx: 
    depends_on: 
      - wordpress
    build: ./requirements/nginx/.
    image: nginx
    container_name: nginx
    env_file:
    - .env
    ports:
    # - "80:80"
    - "443:443"
    networks:
    - inception_network
    volumes:
    - wp-data:/var/www/wordpress/
    # links: 
    # - wordpress
    restart: always

  wordpress: 
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    env_file:
    - .env
    ports:
    - "9000"
    networks:
    - inception_network
    volumes:
    - wp-data:/var/www/wordpress/
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
   wp-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/abbelhac/wp-data"
      o: bind

