version: "3"
services:
 
  nginx: 
    depends_on:
    - mariadb
    - wordpress
    build: ./requirements/nginx/.
    image: nginx
    container_name: nginx
    env_file:
    - .env
    ports:
    # - "80:80"
    - "443:443"
    networks:
    - inception_network
    volumes:
    - wp-data:/var/www/wordpress/
    # links: 
    # - wordpress
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    env_file:
    - .env
    ports:
    - "9000"
    networks:
    - inception_network
    volumes:
    - wp-data:/var/www/wordpress/
    restart: always

  mariadb: 
    build: ./requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    env_file:
    - .env
    ports:
    - "3306"
    networks:
    - inception_network
    volumes:
    - db-data:/var/lib/mysql
    #restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: "/Users/abbelhac/wp-data"
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: "/Users/abbelhac/db-data"
      o: bind